In [1]:
import pandas as pd
import numpy as np
from numpy import log as ln


data = pd.read_csv('../DATA_P/행정동별.csv')
data = pd.DataFrame(data)

#접근성은 제외

data['정보화지수'] = data['전체인구']/data['전체인구'] + data['고령자 수']/data['전체인구']* 0.5 + data['장애인 수']/data['전체인구'] * 0.668 + data['기초 수급자 수']/data['전체인구']*0.853
data['실외 와이파이 비율'] = data['실외 와이파이 수']/data['와이파이 수']
data['전체인구'] = 1/data['전체인구']
data2 = data[['행정동','와이파이 수','실외 와이파이 비율','정보화지수','전체인구','평균소득']]

data = data[['와이파이 수','실외 와이파이 비율','정보화지수','전체인구','평균소득']]

dt = []

for i in range(20) :
    li = []
    for j in data.columns :
        li.append(list(data[j])[i])
    dt.append(li)

data1 = dt

In [2]:
n = len(data1[0])
m = len(data1)

for i in range(n):
    
    cl = []
    
    for j in range(m):
        
        cl.append(data1[j][i])
    
    max_n = max(cl)
    min_n = min(cl)
    
    for j in range(m) :
        data1[j][i] = round((data1[j][i] - min_n) / (max_n - min_n),3)
        


entropy = []

k = 1 / ln(m)

for i in range(n) :
    
    e = []
    
    for j in range(m):
        
        d = data1[j][i]
        if ln(d) == "-inf"  :
            e.append(0)
        else:
            ld = round(ln(d),3)
            if np.isnan(d*ld):
                e.append(0)
            else:
                e.append(d*ld)
        
        
    entropy.append(k * sum(e))
    

weight = []

sum_ent = sum(entropy)

for i in range(n) :
    weight.append(entropy[i]/sum_ent)

print(weight)

[0.18691845819933142, 0.16155219340631488, 0.21438904115376287, 0.2275894657351225, 0.2095508415054683]

<ipython-input-2-8cf31ef43d64>:31: RuntimeWarning: divide by zero encountered in log
  if ln(d) == "-inf"  :
<ipython-input-2-8cf31ef43d64>:34: RuntimeWarning: divide by zero encountered in log
  ld = round(ln(d),3)
<ipython-input-2-8cf31ef43d64>:35: RuntimeWarning: invalid value encountered in double_scalars
  if np.isnan(d*ld):

In [3]:
from sklearn import preprocessing

x = data.values

min_max_scaler = preprocessing.MinMaxScaler()
x_sc = min_max_scaler.fit_transform(x)
data = pd.DataFrame(x_sc)
data[0]

0     1.000000
1     0.079787
2     0.085106
3     0.186170
4     0.074468
5     0.037234
6     0.212766
7     0.000000
8     0.148936
9     0.234043
10    0.047872
11    0.164894
12    0.212766
13    0.319149
14    0.000000
15    0.085106
16    0.106383
17    0.446809
18    0.122340
19    0.101064
Name: 0, dtype: float64

In [4]:
data2['와이파이 설치 지수'] = (weight[0] * data[0] + weight[1] * data[1] + weight[2] * data[2] + weight[3] * data[3] + weight[4] * data[4])*100
data2.sort_values('와이파이 설치 지수')

     행정동  와이파이 수  실외 와이파이 비율     정보화지수      전체인구         평균소득  와이파이 설치 지수
11   염창동      63    0.634921  1.074845  0.000024  5247.045000   25.074558
17  화곡6동     116    0.413793  1.138527  0.000040  4585.700000   25.282918
3    공항동      67    0.835821  1.138855  0.000032  4350.476667   27.100060
19  화곡본동      51    0.823529  1.145056  0.000029  4585.700000   27.239727
13  화곡1동      92    0.847826  1.138610  0.000019  4585.700000   27.372026
12  우장산동      72    0.763889  1.100802  0.000023  5000.365000   27.909187
8   방화1동      60    0.766667  1.128650  0.000023  5186.150000   30.702113
10  방화3동      41    0.658537  1.257754  0.000044  4573.180000   33.474470
15  화곡3동      48    0.812500  1.147544  0.000046  4585.700000   34.301261
18  화곡8동      55    0.890909  1.157439  0.000040  4585.700000   35.443180
16  화곡4동      52    0.769231  1.173644  0.000048  4585.700000   35.573847
14  화곡2동      32    0.812500  1.152110  0.000055  4585.700000   36.944462
9   방화2동      76    0.618421  1.209180  0.000042  5123.665000   39.578040
4   등촌1동      46    0.739130  1.090913  0.000041  5654.740000   40.236936
7   발산1동      32    0.875000  1.129891  0.000027  5972.693333   43.382002
6   등촌3동      72    0.541667  1.346240  0.000033  5654.740000   46.810147
5   등촌2동      39    0.897436  1.119880  0.000049  5654.740000   49.608364
0   가양1동     220    0.713636  1.069123  0.000029  5697.585000   50.913846
2   가양3동      48    0.541667  1.328417  0.000066  5241.120000   52.796799
1   가양2동      47    0.382979  1.464203  0.000071  5241.120000   57.194162

In [7]:
round(np.mean(data2['와이파이 설치 지수']),3)

37.347