In [2]:
import pandas as pd

#가로 쓰레기통 데이터, 자치구단위 서울 생활인구 데이터 import.
#각각 dataframe화 하여 df, df1로 정의
df = pd.read_excel('../DATA/서울특별시 가로쓰레기통 현황_202106.xlsx',header = 1)
df1 = pd.read_csv('../DATA/자치구단위 서울생활인구 일별 집계표.csv', encoding='CP949')

# df에서 '자치구명' column 별로 몇개의 쓰레기통이 있는지 value_counts()로 집계한 dataframe g0 정의
g0 = pd.DataFrame(df['자치구명'].value_counts())

# df1에서'시군구명'column 별로 '총생활인구수' 평균을 구한 dataframe g 정의
g = pd.DataFrame(df1['총생활인구수'].groupby(df1['시군구명']).mean())

# g에서 index가 '서울시' 인 데이터는 필요없으므로 drop하여 제거 후, index 명으로 sort(전처리)
g = g.drop(['서울시']).sort_index()

# g와 g0의 index명을 동일하게 만들기 위해 g0의 '강서'를 g와 동일한 '강서구'로 변경 후, index 명으로 sort(전처리)
g0 = g0.rename(index={'강서':'강서구'}).sort_index()

# 전처리한 g와 g0의 값을 이용해 자치구별로 (쓰레기통 갯수)/(총생활인구수) 비율을 구한 dataframe tp_ratio를 구함. 
tp_ratio = pd.DataFrame(g0['자치구명']/g['총생활인구수'])

#column명을 '비율'로 설정
tp_ratio.columns = ['비율']

#값에 대해 정렬해서 결과값 출력
tp_ratio.sort_values(by=['비율'])

            비율
강동구   0.000151
송파구   0.000160
노원구   0.000173
금천구   0.000187
동대문구  0.000208
중랑구   0.000256
양천구   0.000265
성북구   0.000283
광진구   0.000318
관악구   0.000344
서초구   0.000417
영등포구  0.000439
동작구   0.000446
마포구   0.000488
성동구   0.000489
강서구   0.000515
은평구   0.000518
중구    0.000581
종로구   0.000638
구로구   0.000687
서대문구  0.000733
강북구   0.000808
용산구   0.000856
도봉구   0.000979
강남구   0.001166

In [10]:
#서울 자치구별 가로 쓰레기통 개수 정렬
g0['자치구명'].sort_values() #강서구는 전체 구에서 4번째로 쓰레기통이 많음.

금천구      45
강동구      76
동대문구     80
노원구      91
중랑구      93
양천구     106
송파구     123
광진구     126
성북구     126
관악구     175
성동구     177
동작구     184
중구      185
종로구     201
영등포구    224
은평구     233
마포구     239
강북구     247
서초구     250
용산구     269
도봉구     280
강서구     287
서대문구    290
구로구     292
강남구     976
Name: 자치구명, dtype: int64

In [13]:
#서울 강서구 행정동별 가로쓰레기통 설치 위치
df2 = pd.read_csv('../DATA/서울특별시 강서구_가로쓰레기통 설치 정보_20210901.csv', encoding='CP949')
g2 = pd.DataFrame(df2['설치위치'].value_counts())

      설치위치
가양1동    51
화곡1동    24
공항동     24
발산1동    19
등촌3동    16
화곡6동    16
염창동     16
방화1동    16
가양3동    15
방화2동    14
등촌2동    12
우장산동    11
가양2동    11
등촌1동    10
방화3동    10
화곡본동     6
화곡4동     6
화곡3동     5
화곡2동     3
화곡8동     2

In [118]:
#강서구 주민등록인구 (연령별/동별) 통계
df3 = pd.ExcelFile('../DATA/Report (1).xls')
sheet4 = pd.DataFrame(df3.parse(3))
se = []
for i in range(len(list(sheet4.loc[0]))):
    if list(sheet4.loc[0])[i] == '강서구':
        if list(sheet4.loc[1])[i] != '소계':
            if list(sheet4.loc[2])[i] == '계':
                se.append(list(sheet4)[i])
p = pd.DataFrame(sheet4[se[0]])
for i in range(1,len(se)):
    p = pd.concat([p,pd.DataFrame(sheet4[se[i]])],axis = 1)

sheet1 = pd.DataFrame(df3.parse(0))
p = pd.concat([pd.DataFrame(sheet1['연령']),p],axis=1)
p = p.drop(index=2, axis=0)
p = p.set_index("연령")
p.sort_values(by='0~4세', axis = 1)

TypeError: sum() got an unexpected keyword argument 'index'