In [7]:
import pandas as pd

In [10]:
# csv파일 읽어오기
data = pd.read_csv('C:\\Users\\jiyeon\\Desktop\\백지연\\공모전\\서울특별시강서구_가로쓰레기통_설치정보_20210901.csv', encoding='CP949')
data

,연번,자치구명,도로(가로)명,설치위치,세부위치,설치지점,수거 쓰레기 종류,형태,담당자 연락처
0,1,서울특별시 강서구,가로공원로,화곡1동,나누리병원 16-199,버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067
1,2,서울특별시 강서구,가로공원로,화곡1동,나누리병원 16-200,버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067
2,3,서울특별시 강서구,강서로,화곡1동,까치산역 16-192,버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067
3,4,서울특별시 강서구,강서로,화곡1동,까치산역 16-192,버스정류장,재활용수거,일반쓰레기통,02-2600-4067
4,5,서울특별시 강서구,강서로,화곡1동,화곡역.현대주유소 16-205,버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067
...,...,...,...,...,...,...,...,...,...
282,283,서울특별시 강서구,양천로,염창동,염창동새마을금고 버스정류장(16-247),버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067
283,284,서울특별시 강서구,허준로,가양3동,가양초등학교 버스정류장(16-240),버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067
284,285,서울특별시 강서구,허준로,가양3동,세현고등학교 버스정류장(16-244),버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067
285,286,서울특별시 강서구,공항대로,우장산동,발산역5번출구 버스정류장(16-112),버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067
286,287,서울특별시 강서구,발산로,발산1동,서울특별시 강서구농수산물도매시장 버스정류장(16-975),버스정류장,일반쓰레기 수거용,일반쓰레기통,02-2600-4067

In [14]:
# 도로명 기준 강서구 가로쓰레기통 개수
data_road = pd.DataFrame(data['도로(가로)명'].value_counts())
data_road

         도로(가로)명
양천로           45
공항대로          43
화곡로           41
강서로           27
허준로           19
등촌로           17
방화대로          11
마곡중앙5로        10
개화로            9
곰달래로           8
가로공원로          7
남부순환로          6
마곡중앙로          5
금낭화로           5
양천로59길         5
마곡서1로          4
방화동로           3
마곡중앙10로        3
마곡동로           3
월정로            3
수명로            3
개화동로           2
마곡서로           2
송정로            1
발산로            1
공항대로45길        1
마곡중앙6로         1
김포대로           1
초원로            1

In [15]:
# 행정동 기준 강서구 가로쓰레기통 개수
data_admin = pd.DataFrame(data['설치위치'].value_counts())
data_admin

      설치위치
가양1동    51
화곡1동    24
공항동     24
발산1동    19
등촌3동    16
방화1동    16
화곡6동    16
염창동     16
가양3동    15
방화2동    14
등촌2동    12
우장산동    11
가양2동    11
등촌1동    10
방화3동    10
화곡본동     6
화곡4동     6
화곡3동     5
화곡2동     3
화곡8동     2

In [16]:
# 강서구 가로 쓰레기통의 세부 위치
data_location = pd.DataFrame(data['세부위치'].value_counts())
data_location

                        세부위치
서울특별시 강서구구청 가양동별관          2
마곡엠밸리5단지 버스정류장(16-706)     2
경복여고16-138                 2
하이웨이주유소건너                  2
엠벨리15단지 버스정류장 앞16-428      2
...                      ...
명덕고등학교16-216               1
우장산역 1번출구16-213            1
공항시장16-119                 1
등촌중학교16-104                1
염창동새마을금고 버스정류장(16-247)     1

[229 rows x 1 columns]

In [17]:
# 강서구 가로쓰레기통의 설치지점
data_wh = pd.DataFrame(data['설치지점'].value_counts())
data_wh

        설치지점
버스정류장    215
다중집합장소    37
지하철입구     25
횡단보도       8
대로변        1
도로변        1